import {useEffect,useState,type SubmitEvent} from 'react';
import {api} from './api';
type CareInfo={enrollment:null|{clinic_name:string,nurse_name:string|null,status:string,next_followup:string|null},events:{id:number,author:string,body:string,occurred:string}[]};
export function Care({patientId}:{patientId:string}){
  const [care,setCare]=useState<CareInfo|null>(null),[centers,setCenters]=useState<{id:string,name:string,city:string}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;Promise.all([api<CareInfo>(`/patients/${patientId}/care`),api<{items:{id:string,name:string,city:string}[]}>('/centers')]).then(([c,list])=>{if(active){setCare(c);setCenters(list.items);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[patientId]);
  async function join(event:SubmitEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError('');try{await api(`/patients/${patientId}/care`,{clinicId:data.get('center'),consent:data.get('consent')==='on'});setCare(await api<CareInfo>(`/patients/${patientId}/care`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!care&&!error)return null;
  return <section className="card week-card"><h3>Tu equipo de salud</h3>{error&&<p className="error-box" role="alert">{error}</p>}{care?.enrollment?<><p className="preserve">{care.enrollment.clinic_name}</p><p className="small-copy">{care.enrollment.status==='requested'?'Solicitud enviada. El centro debe aceptar tu seguimiento.':care.enrollment.status==='closed'?'Seguimiento cerrado.':care.enrollment.nurse_name?`Te acompaña ${care.enrollment.nurse_name}`:'Pendiente de asignación del personal de salud.'}</p>{care.enrollment.next_followup&&<p>Próximo seguimiento: {care.enrollment.next_followup}</p>}{care.events.map(e=><article className="care-event" key={e.id}><small>{e.occurred} · {e.author}</small><p>{e.body}</p></article>)}</>:centers.length?<form className="product-form" onSubmit={join}><label>Selecciona tu posta o clínica<select name="center" required><option value="">Seleccionar centro</option>{centers.map(c=><option value={c.id} key={c.id}>{c.name}{c.city?` · ${c.city}`:''}</option>)}</select></label><label className="check-label"><input type="checkbox" name="consent" required/>Autorizo a este centro y a su equipo asignado a consultar este perfil y sus registros para acompañar el seguimiento.</label><button className="action secondary" disabled={busy}>Solicitar seguimiento</button></form>:<p className="small-copy">Aquí podrás vincular el perfil con tu centro cuando esté disponible en Fuerte.</p>}</section>;
}
