import {useState,type SubmitEvent} from 'react';
import {Check,ClipboardList,Heart,Info,MessageCircle,Plus,ShieldCheck,SquarePen,UserRound} from 'lucide-react';

export type RecordItem={id:number,kind:string,occurred:string,body:string};
export const recordLabels:Record<string,string>={dose:'Dosis registrada',difficulty:'Dificultad',note:'Apunte',appointment:'Control médico'};
export const localDate=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Lima'});
const formText=(data:FormData,key:string)=>{const value=data.get(key);return typeof value==='string'?value:'';};
const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('es-PE',{day:'numeric',month:'long',year:'numeric'});

export function DoseCard({name,given,busy,onDose,onHistory,onDifficulty}:{name:string,given:boolean,busy:boolean,onDose:()=>void,onHistory:()=>void,onDifficulty:()=>void}){
  if(given)return <section className="card dose-complete" aria-label="Dosis de hoy registrada"><span className="completion-icon"><Check size={28}/></span><p className="eyebrow">REGISTRO COMPLETADO</p><h2>Dosis registrada</h2><p>La dosis de <strong>{name}</strong> quedó guardada en su historial.</p><p className="completion-date">{dateLabel(localDate())}</p><p className="completion-copy">No necesitas otro paso para guardar este registro.</p><button className="action secondary" disabled={busy} onClick={onHistory}><ClipboardList size={18}/>Ver registro en el historial</button><p className="small-copy">Si necesitas anotar una dificultad, puedes hacerlo desde el historial.</p></section>;
  return <section className="card dose-card"><div className="dose-heading"><div><span className="today-label">HOY · {dateLabel(localDate())}</span><h2>Un paso por {name}</h2></div><span className="drop-circle"><Heart/></span></div><p>Registra la dosis después de administrarla según la pauta del profesional.</p><button className="action primary" disabled={busy} onClick={onDose}><Check/>Ya recibió su dosis</button><button className="action secondary" disabled={busy} onClick={onDifficulty}>Tuve una dificultad</button></section>;
}

export function TreatmentCard({name,treatment,busy,onSave}:{name:string,treatment:string,busy:boolean,onSave:(value:string)=>Promise<void>}){
  const [editing,setEditing]=useState(false),[error,setError]=useState('');
  async function save(e:SubmitEvent<HTMLFormElement>){e.preventDefault();const value=formText(new FormData(e.currentTarget),'treatment').trim();if(!value){setError('Copia la indicación antes de guardarla.');return;}setError('');try{await onSave(value);setEditing(false);}catch(err){setError((err as Error).message);}}
  return <section className="card week-card treatment-card"><div className="section-title"><h3>La pauta que registraste</h3>{editing&&<button className="text-button" disabled={busy} onClick={()=>{setEditing(false);setError('');}}>Cancelar</button>}</div>{editing?<><p className="small-copy">Indicaciones para <strong>{name}</strong></p>{error&&<p className="error-box" role="alert">{error}</p>}<form className="product-form" onSubmit={save}><label>Copia la indicación de tu profesional<textarea name="treatment" defaultValue={treatment} maxLength={2000} required disabled={busy} placeholder="Copia la indicación tal como la recibiste."/></label><p className="small-copy">No modifiques ni completes dosis por tu cuenta.</p><button className="action primary" disabled={busy}><Check size={18}/>{busy?'Guardando…':'Guardar indicaciones'}</button></form></>:<>{!treatment&&<span className="empty-pauta-icon"><ClipboardList/></span>}<p className="preserve">{treatment||'Todavía no registraste una pauta.'}</p>{!treatment&&<p className="small-copy">Ten a mano las indicaciones de su profesional de salud para copiarlas aquí.</p>}<button className="action primary" disabled={busy} onClick={()=>setEditing(true)}><SquarePen size={18}/>{treatment?'Actualizar indicaciones':'Registrar indicaciones'}</button><p className="small-copy treatment-note">La pauta corresponde a {name}. Fuerte no calcula ni cambia las dosis.</p></>}</section>;
}

export function PatientIdentity({user,patient,patients,selected,busy,onSelect,onCreate}:{user:string,patient?:{name:string},patients:{id:string,name:string}[],selected:string,busy:boolean,onSelect:(id:string)=>void,onCreate:()=>void}){
  return <div className="caregiver-context"><div className="caregiver-account"><span className="account-mark"><UserRound size={19}/></span><div><p className="eyebrow">TU CUENTA DE CUIDADOR</p><strong>{user}</strong></div></div>{patients.length>0&&<section className="patient-context"><label className="eyebrow" htmlFor="patient">NIÑO O NIÑA AL QUE ACOMPAÑAS</label><div className="profile-picker"><select id="patient" disabled={busy} value={selected} onChange={e=>onSelect(e.target.value)}>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="icon-button" disabled={busy} aria-label="Añadir perfil infantil" onClick={onCreate}><Plus/></button></div>{patient&&<p className="small-copy">Las dosis, indicaciones y registros que ves corresponden a <strong>{patient.name}</strong>.</p>}</section>}</div>;
}

export function ChatConsent({consent,busy,onChange,onSkip}:{consent:boolean,busy:boolean,onChange:(value:boolean)=>void,onSkip:()=>void}){
  return <section className="card privacy-card" aria-label="Autorización del asistente"><div className="privacy-title"><ShieldCheck size={25}/><h3>Tú decides qué compartir</h3></div><p>Para responder con contexto, el asistente necesita consultar información de este perfil.</p><ul className="privacy-data"><li><MessageCircle size={18}/><span><strong>Tu consulta y conversación reciente.</strong> Para entender lo que estás preguntando.</span></li><li><ClipboardList size={18}/><span><strong>La pauta y los registros recientes.</strong> También su fecha de nacimiento, resúmenes del historial y el seguimiento compartido por tu equipo de salud.</span></li></ul><p><strong>¿Quién los recibe?</strong> OpenAI, el proveedor de IA que genera la respuesta.</p><details><summary>Qué significa autorizar el chat</summary><p>Estos datos se envían a un servicio externo al enviar cada consulta. No escribas DNI, direcciones ni otros datos innecesarios. Puedes seguir usando las demás funciones sin autorizar el chat.</p></details><label className="privacy-check"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>onChange(e.target.checked)}/><span>Autorizo enviar estos datos a OpenAI para responder mis consultas.</span></label><button className="text-button" disabled={busy} onClick={onSkip}>Seguir sin usar el chat</button></section>;
}

export function HistoryPanel({records,cursor,busy,name,initialKind,onSave,onMore}:{records:RecordItem[],cursor:number|null,busy:boolean,name:string,initialKind?:string,onSave:(kind:string,body:string,date:string)=>Promise<void>,onMore:()=>void}){
  const [adding,setAdding]=useState(!!initialKind),[filter,setFilter]=useState('all'),[error,setError]=useState('');
  const filtered=records.filter(r=>filter==='all'||r.kind===filter);
  async function save(e:SubmitEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget),body=formText(data,'body').trim();if(!body){setError('Escribe qué ocurrió antes de guardar.');return;}setError('');try{await onSave(formText(data,'kind'),body,formText(data,'occurred'));setAdding(false);setFilter('all');}catch(err){setError((err as Error).message);}}
  if(adding)return <section className="card week-card record-editor"><div className="section-title"><h2>Agregar un registro</h2><button className="text-button" disabled={busy} onClick={()=>{setAdding(false);setError('');}}>Cancelar</button></div><p className="small-copy">Para <strong>{name}</strong></p>{error&&<p role="alert" className="error-box">{error}</p>}<form className="product-form" onSubmit={save}><label>Qué quieres registrar<select name="kind" defaultValue={initialKind||'note'} disabled={busy}><option value="note">Un apunte u observación</option><option value="difficulty">Una dificultad con la dosis</option><option value="appointment">Un control médico</option><option value="dose">Una dosis anterior</option></select></label><label>Fecha<input name="occurred" type="date" defaultValue={localDate()} required disabled={busy}/></label><label>Detalle<textarea name="body" required maxLength={2000} disabled={busy} placeholder="Qué ocurrió o qué indicó el profesional"/></label><button className="action primary" disabled={busy}><Check size={18}/>{busy?'Guardando…':'Guardar registro'}</button></form></section>;
  return <section className="history-overview" aria-label="Historial"><div className="history-toolbar"><div><h2>Sus registros</h2><p className="small-copy">{records.length} registros{cursor?' cargados':''}</p></div><button className="action primary compact-action" disabled={busy} onClick={()=>setAdding(true)}><Plus size={17}/>Agregar registro</button></div><fieldset className="history-filters"><legend className="sr-only">Filtrar registros</legend>{[['all','Todos'],['dose','Dosis'],['note','Apuntes'],['appointment','Controles'],['difficulty','Dificultades']].map(([key,label])=><button key={key} type="button" aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</fieldset><section className="history-list" aria-label="Registros anteriores">{filtered.length===0&&<div className="empty history-empty"><ClipboardList size={28}/><p>{records.length?'No hay registros de esta categoría entre los cargados.':'Tu historia comienza con el primer registro.'}</p></div>}{filtered.map(r=><article key={r.id}><span className="history-dot"/><div><small>{dateLabel(r.occurred)}</small><h3>{recordLabels[r.kind]}</h3><p className="preserve">{r.body}</p></div></article>)}</section>{cursor&&<><p className="small-copy">Los filtros se aplican a los registros cargados. Puedes consultar más entradas.</p><button className="action secondary" disabled={busy} onClick={onMore}>{busy?'Cargando…':'Ver registros anteriores'}</button></>}<p className="history-hint"><Info size={16}/>Abre «Agregar registro» cuando quieras anotar algo nuevo.</p></section>;
}
