/* eslint-disable next/no-img-element -- Static Vite entry; no Next image server. */
import {createRoot} from 'react-dom/client';
import {useEffect,useState,lazy,Suspense,type SubmitEvent} from 'react';
import {Heart,House,MessageCircle,ClipboardList,LogOut,Plus,Check} from 'lucide-react';
import '../app/globals.css';
import './product.css';
import {Week} from './Week';
import {Care} from './Care';
import type {Workspace} from './Clinical';
const Clinical=lazy(()=>import('./Clinical'));
type Patient={id:string,name:string,birth_date:string,treatment:string,version:number};
type RecordItem={id:number,kind:string,occurred:string,body:string};
type Message={id?:number,role:string,body:string};
const labels:Record<string,string>={dose:'Dosis registrada',difficulty:'Dificultad',note:'Apunte',appointment:'Control médico'};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Lima'});
async function api<T=unknown>(path:string,body?:unknown,method='POST',key?:string){const response=await fetch('/api/v1'+path,{method:body===undefined?'GET':method,headers:body===undefined?{}:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json() as {error?:{message?:string}};if(!response.ok)throw new Error(data.error?.message||'No pudimos completar la operación.');return data as T;}
function field(data:FormData,key:string){const value=data.get(key);return typeof value==='string'?value:'';}
function App(){
  const [workspace,setWorkspace]=useState<Workspace|null>(null),[clinical,setClinical]=useState(false);
  const [user,setUser]=useState<{name:string}|null>(null),[loading,setLoading]=useState(true),[signup,setSignup]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [patients,setPatients]=useState<Patient[]>([]),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[tab,setTab]=useState('inicio'),[records,setRecords]=useState<RecordItem[]>([]),[cursor,setCursor]=useState<number|null>(null),[messages,setMessages]=useState<Message[]>([]),[available,setAvailable]=useState(false),[consent,setConsent]=useState(false),[notice,setNotice]=useState('');
  useEffect(()=>{if(!user)return;let active=true;api<Workspace>('/workspace').then(w=>{if(active){setWorkspace(w);if(w.superadmin||w.memberships.length)setClinical(true);}}).catch(()=>{});return()=>{active=false;};},[user]);
  const patient=patients.find(p=>p.id===selected);
  const loadPatients=async()=>{const data=await api<{items:Patient[]}>('/patients');setPatients(data.items);setSelected(prev=>data.items.some((p:Patient)=>p.id===prev)?prev:data.items[0]?.id||'');};
  const loadRecords=async(id:string)=>{const data=await api<{items:RecordItem[],nextCursor:number|null}>(`/patients/${id}/records`);setRecords(data.items);setCursor(data.nextCursor);};
  useEffect(()=>{api<{user:{name:string}}>('/me').then(async data=>{setUser(data.user);await loadPatients();}).catch(()=>{}).finally(()=>setLoading(false));},[]);
  // eslint-disable-next-line react/react-compiler -- Clear the previous profile immediately before fetching its replacement.
  useEffect(()=>{setRecords([]);setMessages([]);setError('');setConsent(false);if(!selected)return;let active=true;Promise.all([api<{items:RecordItem[],nextCursor:number|null}>(`/patients/${selected}/records`),api<{items:Message[],available:boolean}>(`/patients/${selected}/chat`)]).then(([r,c])=>{if(active){setRecords(r.items);setCursor(r.nextCursor);setMessages(c.items);setAvailable(c.available);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[selected]);
  async function action(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const submit=(fn:(data:FormData,form:HTMLFormElement)=>Promise<void>)=>(event:SubmitEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;void action(()=>fn(new FormData(form),form));};
  async function record(kind:string,body:string,occurred=today()){await api(`/patients/${selected}/records`,{kind,body,occurred},'POST',crypto.randomUUID());await loadRecords(selected);setNotice('Registro guardado en tu historial.');}
  if(user&&clinical&&workspace)return <Suspense fallback={<output>Cargando panel de salud…</output>}><Clinical workspace={workspace} onCaregiver={()=>setClinical(false)} onLogout={()=>void action(async()=>{await api('/logout',{});setUser(null);setPatients([]);setSelected('');setWorkspace(null);setClinical(false);})}/></Suspense>;
  return <div className="phone-shell"><header className="app-header"><div className="brand"><img src="/assets/logo.png" alt=""/><div><strong>Fuerte</strong><span><i/>Un paso a la vez</span></div></div>{user&&<button className="icon-button" aria-label="Cerrar sesión" disabled={busy} onClick={()=>void action(async()=>{await api('/logout',{});setUser(null);setPatients([]);setSelected('');setRecords([]);setMessages([]);})}><LogOut size={20}/></button>}</header><main id="main" className="app-main">
    {error&&<div role="alert" className="error-box">{error}</div>}{notice&&<output className="success">{notice}</output>}
    {loading?<output>Cargando tu espacio…</output>:!user?<><div className="welcome-art"><img src="/assets/family.jpg" alt="Ilustración de una familia"/></div><div className="page-intro"><p className="eyebrow">CUIDAR, ACOMPAÑAR, AVANZAR</p><h1>Cada pequeño paso cuenta.</h1><p>Un espacio para acompañar el tratamiento de la anemia y recordar lo que importa.</p></div><form className="product-form" onSubmit={submit(async data=>{const result=await api<{user:{name:string}}>(signup?'/signup':'/login',{email:data.get('email'),password:data.get('password'),name:data.get('name'),consent:data.get('consent')==='on'});setUser(result.user);await loadPatients();})}>{signup&&<label>Tu nombre<input name="name" autoComplete="name" required maxLength={80}/></label>}<label>Correo electrónico<input name="email" type="email" autoComplete="email" required/></label><label>Contraseña<input name="password" type="password" autoComplete={signup?'new-password':'current-password'} minLength={signup?12:1} maxLength={128} required/></label>{signup&&<><p className="small-copy">Usa al menos 12 caracteres. Esta primera versión aún no permite recuperar contraseñas por correo.</p><label className="check-label"><input name="consent" type="checkbox" required/>Soy responsable de los datos que registre y acepto guardarlos en Fuerte para realizar el seguimiento.</label><p className="small-copy">Los datos se almacenan en el servidor del proyecto. Solo se envía contexto a OpenAI si autorizas el chat. No registres DNI, direcciones ni información innecesaria.</p></>}<button className="action primary" disabled={busy}>{busy?'Un momento…':signup?'Crear mi cuenta':'Entrar'}</button></form><button className="text-button" onClick={()=>{setSignup(!signup);setError('');}}>{signup?'Ya tengo una cuenta':'Crear una cuenta'}</button></>:<>
    {workspace&&(workspace.superadmin||workspace.memberships.length>0)&&<button className="action secondary" onClick={()=>setClinical(true)}>Abrir panel de salud</button>}
    <div className="greeting"><div><p>Hola, {user.name}</p><h1>{tab==='chat'?'Estamos para acompañarte':tab==='historial'?'Cada paso, en tu historia':'Sigamos cuidando juntos'}</h1></div></div>
    {patients.length>0&&<div className="profile-picker"><label className="sr-only" htmlFor="patient">Perfil del niño o niña</label><select id="patient" disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setCreating(false);}}>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="icon-button" disabled={busy} aria-label="Añadir perfil" onClick={()=>setCreating(!creating)}><Plus/></button></div>}
    {(creating||!patients.length)&&<section className="card week-card"><h2>Su espacio de cuidado</h2><p className="small-copy">Registra a quien acompañas. Copia únicamente la pauta indicada por su profesional de salud.</p><form className="product-form" onSubmit={submit(async(data,form)=>{const p=await api<Patient>('/patients',{name:data.get('name'),birthDate:data.get('birth'),treatment:data.get('treatment')});await loadPatients();setSelected(p.id);setCreating(false);form.reset();})}><label>Nombre o apodo<input name="name" required maxLength={80}/></label><label>Fecha de nacimiento<input type="date" name="birth" max={today()} required/></label><label>Pauta indicada por el profesional<textarea name="treatment" maxLength={2000} placeholder="Medicamento, indicaciones y fecha del control, si los tienes."/></label><button className="action primary" disabled={busy}>Guardar perfil</button></form></section>}
    {patient&&!creating&&<>
    {tab==='inicio'&&<><section className="card dose-card"><div className="dose-heading"><div><span className="today-label">HOY · {today()}</span><h2>Un paso por {patient.name}</h2></div><span className="drop-circle"><Heart/></span></div><p>Registra la dosis después de administrarla según la pauta del profesional.</p>{records.some(r=>r.kind==='dose'&&r.occurred===today())?<div className="success"><Check size={16}/> Ya hay una dosis registrada hoy.</div>:<button className="action primary" disabled={busy} onClick={()=>void action(()=>record('dose','El cuidador confirmó la administración según la pauta indicada.'))}><Check/>Ya recibió su dosis</button>}<button className="action secondary" onClick={()=>setTab('historial')}>Tuve una dificultad</button></section><Week key={patient.id} patientId={patient.id} revision={records} onHistory={()=>setTab('historial')}/><Care key={'care-'+patient.id} patientId={patient.id}/><section className="card week-card"><h3>La pauta que registraste</h3><p className="preserve">{patient.treatment||'Todavía no registraste una pauta.'}</p><details><summary>Actualizar indicaciones registradas</summary><form key={patient.id+patient.version} className="product-form" onSubmit={submit(async data=>{await api(`/patients/${selected}`,{treatment:data.get('treatment'),version:patient.version},'PATCH');await loadPatients();setNotice('Indicaciones guardadas.');})}><label>Copia la indicación de tu profesional<textarea name="treatment" defaultValue={patient.treatment} maxLength={2000}/></label><button className="action secondary" disabled={busy}>Guardar indicaciones</button></form></details></section><div className="tip-card"><Heart/><p>No cambies ni compenses dosis por tu cuenta. Ante dudas sobre el tratamiento, consulta con el profesional que lo indicó.</p></div></>}
    {tab==='historial'&&<><section className="card week-card"><h2>Agregar un registro</h2><form className="product-form" onSubmit={submit(async(data,form)=>{await record(field(data,'kind'),field(data,'body'),field(data,'occurred'));form.reset();})}><label>Qué quieres registrar<select name="kind"><option value="difficulty">Una dificultad con la dosis</option><option value="note">Un apunte u observación</option><option value="appointment">Un control médico</option><option value="dose">Una dosis anterior</option></select></label><label>Fecha<input name="occurred" type="date" defaultValue={today()} required/></label><label>Detalle<textarea name="body" required maxLength={2000} placeholder="Qué ocurrió o qué indicó el profesional"/></label><button className="action primary" disabled={busy}>Guardar registro</button></form></section><section className="history-list" aria-label="Historial">{records.length===0&&<p className="empty">Tu historia comienza con el primer registro.</p>}{records.map(r=><article key={r.id}><span className="history-dot"/><div><small>{r.occurred}</small><h3>{labels[r.kind]}</h3><p>{r.body}</p></div></article>)}</section>{cursor&&<button className="action secondary" disabled={busy} onClick={()=>void action(async()=>{const data=await api<{items:RecordItem[],nextCursor:number|null}>(`/patients/${selected}/records?before=${cursor}`);setRecords(prev=>[...prev,...data.items]);setCursor(data.nextCursor);})}>Ver registros anteriores</button>}</>}
    {tab==='chat'&&<><div className="tip-card"><MessageCircle/><p>El asistente consulta las indicaciones y registros de este perfil. Puede equivocarse y no sustituye al profesional de salud.</p></div>{!available&&<p className="error-box">Estamos preparando la conexión del asistente. Ya puedes guardar tus registros.</p>}<div className="chat-history" aria-live="polite">{messages.length===0&&<p className="empty">Puedes preguntar: «¿Qué dificultades registré esta semana?»</p>}{messages.map((m,i)=><article key={m.id||i} className={`bubble ${m.role}`}><small>{m.role==='user'?'Tú':'Fuerte'}</small><p>{m.body}</p></article>)}</div><form className="product-form" onSubmit={submit(async(data,form)=>{const message=field(data,'message');const result=await api<{answer:string}>(`/patients/${selected}/chat`,{message,consent});setMessages(prev=>[...prev,{role:'user',body:message},{role:'assistant',body:result.answer}]);form.reset();})}><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Autorizo enviar a OpenAI esta consulta, las indicaciones, registros recientes y conversación de este perfil para responderme.</label><label>Tu mensaje<textarea name="message" maxLength={1500} required placeholder="¿Qué te gustaría saber de tus registros?"/></label><button className="action primary" disabled={busy||!consent||!available}>{busy?'Consultando tus registros…':'Enviar mensaje'}</button></form></>}
    </>}
    </>}
  </main>{user&&<nav className="bottom-nav" aria-label="Navegación principal">{[['inicio','Inicio',House],['historial','Historial',ClipboardList],['chat','Acompañamiento',MessageCircle]].map(([key,label,Icon])=><button key={String(key)} disabled={busy} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(String(key));setCreating(false);setError('');setNotice('');}}><Icon/>{String(label)}</button>)}</nav>}</div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
