/* eslint-disable next/no-img-element -- Static Vite entry; no Next image server. */
import {createRoot} from 'react-dom/client';
import {useEffect,useState,lazy,Suspense,type SubmitEvent} from 'react';
import {Heart,House,MessageCircle,ClipboardList,LogOut} from 'lucide-react';
import '../app/globals.css';
import './product.css';
import {Week} from './Week';
import {Care} from './Care';
import {DoseCard,TreatmentCard,PatientIdentity,ChatConsent,HistoryPanel,type RecordItem} from './Caregiver';
import type {Workspace} from './Clinical';
const Clinical=lazy(()=>import('./Clinical'));
type Patient={id:string,name:string,birth_date:string,treatment:string,version:number};
type WeekData={days:{date:string,status:string}[]};
type Message={id?:number,role:string,body:string};

const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Lima'});
async function api<T=unknown>(path:string,body?:unknown,method='POST',key?:string){const response=await fetch('/api/v1'+path,{method:body===undefined?'GET':method,headers:body===undefined?{}:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json() as {error?:{message?:string}};if(!response.ok)throw new Error(data.error?.message||'No pudimos completar la operación.');return data as T;}
function field(data:FormData,key:string){const value=data.get(key);return typeof value==='string'?value:'';}
function App(){
  const [workspace,setWorkspace]=useState<Workspace|null>(null),[clinical,setClinical]=useState(false);
  const [user,setUser]=useState<{name:string}|null>(null),[loading,setLoading]=useState(true),[signup,setSignup]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [patients,setPatients]=useState<Patient[]>([]),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[tab,setTab]=useState('inicio'),[records,setRecords]=useState<RecordItem[]>([]),[cursor,setCursor]=useState<number|null>(null),[messages,setMessages]=useState<Message[]>([]),[available,setAvailable]=useState(false),[consent,setConsent]=useState(false),[notice,setNotice]=useState('');
  useEffect(()=>{if(!user)return;let active=true;api<Workspace>('/workspace').then(w=>{if(active){setWorkspace(w);if(w.superadmin||w.memberships.length)setClinical(true);}}).catch(()=>{});return()=>{active=false;};},[user]);
  const [recordsPatient,setRecordsPatient]=useState(''),[doseDate,setDoseDate]=useState(''),[refresh,setRefresh]=useState(0),[historyKind,setHistoryKind]=useState<string|undefined>();
  const patient=patients.find(p=>p.id===selected);
  const navigate=(next:string,kind?:string)=>{setTab(next);setHistoryKind(kind);setCreating(false);setError('');setNotice('');};
  async function persist(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}finally{setBusy(false);}}

  const loadPatients=async()=>{const data=await api<{items:Patient[]}>('/patients');setPatients(data.items);setSelected(prev=>data.items.some((p:Patient)=>p.id===prev)?prev:data.items[0]?.id||'');};
  const loadRecords=async(id:string)=>{const [data,week]=await Promise.all([api<{items:RecordItem[],nextCursor:number|null}>(`/patients/${id}/records`),api<WeekData>(`/patients/${id}/week`)]);setRecords(data.items);setCursor(data.nextCursor);setDoseDate(week.days.find(d=>d.date===today()&&d.status==='given')?.date||'');};
  useEffect(()=>{api<{user:{name:string}}>('/me').then(async data=>{setUser(data.user);await loadPatients();}).catch(()=>{}).finally(()=>setLoading(false));},[]);
  // eslint-disable-next-line react/react-compiler -- Clear the previous profile immediately before fetching its replacement.
  useEffect(()=>{setRecords([]);setMessages([]);setError('');setNotice('');setConsent(false);setHistoryKind(undefined);setRecordsPatient('');if(!selected)return;let active=true;Promise.all([api<{items:RecordItem[],nextCursor:number|null}>(`/patients/${selected}/records`),api<{items:Message[],available:boolean}>(`/patients/${selected}/chat`),api<WeekData>(`/patients/${selected}/week`)]).then(([r,c,w])=>{if(active){setRecords(r.items);setCursor(r.nextCursor);setMessages(c.items);setAvailable(c.available);setDoseDate(w.days.find(d=>d.date===today()&&d.status==='given')?.date||'');setRecordsPatient(selected);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[selected,refresh]);
  async function action(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const submit=(fn:(data:FormData,form:HTMLFormElement)=>Promise<void>)=>(event:SubmitEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;void action(()=>fn(new FormData(form),form));};
  async function record(kind:string,body:string,occurred=today()){await api(`/patients/${selected}/records`,{kind,body,occurred},'POST',crypto.randomUUID());await loadRecords(selected);setNotice('Registro guardado en tu historial.');}
  if(user&&clinical&&workspace)return <Suspense fallback={<output>Cargando panel de salud…</output>}><Clinical workspace={workspace} onCaregiver={()=>setClinical(false)} onLogout={()=>void action(async()=>{await api('/logout',{});setUser(null);setPatients([]);setSelected('');setWorkspace(null);setClinical(false);})}/></Suspense>;
  return <div className="phone-shell"><header className="app-header"><div className="brand"><img src="/assets/logo.png" alt=""/><div><strong>Fuerte</strong><span><i/>Un paso a la vez</span></div></div>{user&&<button className="icon-button" aria-label="Cerrar sesión" disabled={busy} onClick={()=>void action(async()=>{await api('/logout',{});setUser(null);setPatients([]);setSelected('');setRecords([]);setMessages([]);})}><LogOut size={20}/></button>}</header><main id="main" className="app-main">
    {error&&<div role="alert" className="error-box">{error}</div>}{notice&&<output className="success">{notice}</output>}
    {loading?<output>Cargando tu espacio…</output>:!user?<><div className="welcome-art"><img src="/assets/family.jpg" alt="Ilustración de una familia"/></div><div className="page-intro"><p className="eyebrow">CUIDAR, ACOMPAÑAR, AVANZAR</p><h1>Cada pequeño paso cuenta.</h1><p>Un espacio para acompañar el tratamiento de la anemia y recordar lo que importa.</p></div><form className="product-form" onSubmit={submit(async data=>{const result=await api<{user:{name:string}}>(signup?'/signup':'/login',{email:data.get('email'),password:data.get('password'),name:data.get('name'),consent:data.get('consent')==='on'});setUser(result.user);await loadPatients();})}>{signup&&<label>Tu nombre<input name="name" autoComplete="name" required maxLength={80}/></label>}<label>Correo electrónico<input name="email" type="email" autoComplete="email" required/></label><label>Contraseña<input name="password" type="password" autoComplete={signup?'new-password':'current-password'} minLength={signup?12:1} maxLength={128} required/></label>{signup&&<><p className="small-copy">Usa al menos 12 caracteres. Esta primera versión aún no permite recuperar contraseñas por correo.</p><label className="check-label"><input name="consent" type="checkbox" required/>Soy responsable de los datos que registre y acepto guardarlos en Fuerte para realizar el seguimiento.</label><p className="small-copy">Los datos se almacenan en el servidor del proyecto. Solo se envía contexto a OpenAI si autorizas el chat. No registres DNI, direcciones ni información innecesaria.</p></>}<button className="action primary" disabled={busy}>{busy?'Un momento…':signup?'Crear mi cuenta':'Entrar'}</button></form><button className="text-button" onClick={()=>{setSignup(!signup);setError('');}}>{signup?'Ya tengo una cuenta':'Crear una cuenta'}</button></>:<>
    {workspace&&(workspace.superadmin||workspace.memberships.length>0)&&<button className="action secondary" onClick={()=>setClinical(true)}>Abrir panel de salud</button>}
    <div className="greeting"><div><h1>{tab==='chat'?'Estamos para acompañarte':tab==='historial'?'Cada paso, en su historia':'Sigamos cuidando juntos'}</h1></div></div>
    <PatientIdentity user={user.name} patient={creating?undefined:patient} patients={patients} selected={selected} busy={busy} onSelect={id=>{setSelected(id);setCreating(false);}} onCreate={()=>setCreating(!creating)}/>

    {(creating||!patients.length)&&<section className="card week-card"><h2>Su espacio de cuidado</h2><p className="small-copy">Registra a quien acompañas. Copia únicamente la pauta indicada por su profesional de salud.</p><form className="product-form" onSubmit={submit(async(data,form)=>{const p=await api<Patient>('/patients',{name:data.get('name'),birthDate:data.get('birth'),treatment:data.get('treatment')});await loadPatients();setSelected(p.id);setCreating(false);form.reset();})}><label>Nombre o apodo<input name="name" required maxLength={80}/></label><label>Fecha de nacimiento<input type="date" name="birth" max={today()} required/></label><label>Pauta indicada por el profesional<textarea name="treatment" maxLength={2000} placeholder="Medicamento, indicaciones y fecha del control, si los tienes."/></label><button className="action primary" disabled={busy}>Guardar perfil</button></form></section>}
    {patient&&!creating&&recordsPatient!==selected&&<section aria-live="polite">{error?<button className="action secondary" onClick={()=>setRefresh(v=>v+1)}>Volver a cargar este perfil</button>:<output>Cargando los registros de {patient.name}…</output>}</section>}
    {patient&&!creating&&recordsPatient===selected&&<>
    {tab==='inicio'&&<><DoseCard name={patient.name} given={doseDate===today()} busy={busy} onDose={()=>void action(()=>record('dose','El cuidador confirmó la administración según la pauta indicada.'))} onHistory={()=>navigate('historial')} onDifficulty={()=>navigate('historial','difficulty')}/><Week key={patient.id} patientId={patient.id} revision={records} onHistory={()=>navigate('historial')}/><Care key={'care-'+patient.id} patientId={patient.id}/><TreatmentCard key={patient.id} name={patient.name} treatment={patient.treatment} busy={busy} onSave={value=>persist(async()=>{await api(`/patients/${selected}`,{treatment:value,version:patient.version},'PATCH');await loadPatients();setNotice('Indicaciones guardadas para '+patient.name+'.');})}/><div className="tip-card"><Heart/><p>No cambies ni compenses dosis por tu cuenta. Ante dudas sobre el tratamiento, consulta con el profesional que lo indicó.</p></div></>}

    {tab==='historial'&&<HistoryPanel key={patient.id+':'+(historyKind||'list')} records={records} cursor={cursor} busy={busy} name={patient.name} initialKind={historyKind} onSave={(kind,body,date)=>persist(()=>record(kind,body,date))} onMore={()=>void action(async()=>{const data=await api<{items:RecordItem[],nextCursor:number|null}>(`/patients/${selected}/records?before=${cursor}`);setRecords(prev=>[...prev,...data.items]);setCursor(data.nextCursor);})}/>}

    {tab==='chat'&&<><ChatConsent consent={consent} busy={busy} onChange={setConsent} onSkip={()=>{setConsent(false);navigate('historial');}}/><div className="tip-card"><MessageCircle/><p>El asistente consulta las indicaciones y registros de este perfil. Puede equivocarse y no sustituye al profesional de salud.</p></div>{!available&&<p className="error-box">Estamos preparando la conexión del asistente. Ya puedes guardar tus registros.</p>}<div className="chat-history" aria-live="polite">{messages.length===0&&<p className="empty">Puedes preguntar: «¿Qué dificultades registré esta semana?»</p>}{messages.map((m,i)=><article key={m.id||i} className={`bubble ${m.role}`}><small>{m.role==='user'?'Tú':'Asistente IA de Fuerte'}</small><p>{m.body}</p></article>)}</div><form className="product-form" onSubmit={submit(async(data,form)=>{if(!consent)throw new Error('Autoriza el envío de datos antes de usar el asistente.');const message=field(data,'message');const result=await api<{answer:string}>(`/patients/${selected}/chat`,{message,consent});setMessages(prev=>[...prev,{role:'user',body:message},{role:'assistant',body:result.answer}]);form.reset();})}><label>Tu mensaje<textarea name="message" maxLength={1500} required placeholder="¿Qué te gustaría saber de tus registros?"/></label><button className="action primary" disabled={busy||!consent||!available}>{busy?'Consultando tus registros…':'Enviar mensaje'}</button></form></>}
    </>}
    </>}
  </main>{user&&<nav className="bottom-nav" aria-label="Navegación principal">{[['inicio','Inicio',House],['historial','Historial',ClipboardList],['chat','Acompañamiento',MessageCircle]].map(([key,label,Icon])=><button key={String(key)} disabled={busy} aria-current={tab===key?'page':undefined} onClick={()=>navigate(String(key))}><Icon/>{String(label)}</button>)}</nav>}</div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
