import {useEffect,useState} from 'react';
import {Search,Users} from 'lucide-react';
import {api} from './api';
type Person={id:string,name:string,email:string,created:string,profiles:number,superadmin:number,staff_centers:string|null,family_centers:string|null};
type Result={items:Person[],nextCursor:number|null,total:number};
export function PlatformUsers(){const [data,setData]=useState<Result>({items:[],nextCursor:null,total:0}),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;api<Result>('/platform/users?q='+encodeURIComponent(search)).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[search]);
 async function more(){setBusy(true);try{const r=await api<Result>(`/platform/users?q=${encodeURIComponent(search)}&after=${data.nextCursor}`);setData(previous=>({...r,items:[...previous.items,...r.items]}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="clinic-panel"><div className="clinic-section-heading"><div><h2>Usuarios de la plataforma</h2><p>{data.total} cuentas registradas. Los roles profesionales se gestionan dentro de cada centro.</p></div><Users/></div>{error&&<p className="error-box" role="alert">{error}</p>}<form className="clinic-search" onSubmit={e=>{e.preventDefault();setSearch(query);}}><Search size={18}/><input aria-label="Buscar usuario" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100} placeholder="Nombre o correo"/><button>Buscar</button></form><div className="clinic-table-wrap"><table className="clinic-table"><thead><tr><th>Usuario</th><th>Tipo de acceso</th><th>Centros del profesional</th><th>Centros de sus perfiles</th><th>Perfiles a cargo</th></tr></thead><tbody>{data.items.map(person=><tr key={person.id}><td><strong>{person.name}</strong><small>{person.email}</small></td><td>{person.superadmin?'Superadministrador':person.staff_centers?'Personal de salud':'Cuidador / cuenta nueva'}</td><td>{person.staff_centers||'Sin asignación'}</td><td>{person.family_centers||'Sin vinculación'}</td><td>{person.profiles}</td></tr>)}</tbody></table></div>{!data.items.length&&<p className="clinic-empty">No hay usuarios que coincidan con la búsqueda.</p>}{data.nextCursor&&<button className="clinic-secondary" disabled={busy} onClick={()=>void more()}>Ver más usuarios</button>}</section>;
}
